apps/app1/views.py
from datetime import datetime
from flask import session, Blueprint, jsonify, request, url_for, redirect, render_template, flash

from flask_login import current_user, login_required

import database.database as db
import stage


from models import USERS  # FIXME: remove this after debugging

app1 = Blueprint('app1', __name__, template_folder="templates/")


@app1.route("/")
def base():
    return redirect(url_for('app1.home'))


@app1.app_errorhandler(404)
def page_not_found(e):
    return render_template('/error_pages/404.html'), 404


@app1.app_errorhandler(500)
def page_not_found(e):
    return render_template('/error_pages/500.html'), 500


@app1.route("/animalsearch/", methods=('GET', 'POST'))
@login_required
def animal_search():
    content = dict()

    content['coat_colors'] = db.get_coat_colors()
    content['coat_color_filter_value'] = ""

    content['sexes'] = db.get_sexes()

    if request.method == 'POST':

        # add parameters to query
        form_data = request.form.to_dict()

      #  print("DEBUG!!!!!!!")
      #  print(form_data)

        name = None
        reg_num = None
        flock = None
        coat_color = None


        if form_data['name-filter'] != '':
            name = form_data['name-filter']
            content['name_filter_value'] = name

        if form_data['regNum-filter'] != '':
            reg_num = form_data['regNum-filter']
            content['reg_num_filter_value'] = reg_num

        if form_data['flock-filter'] != '':
            flock = form_data['flock-filter']
            content['flock_filter_value'] = flock

        # if form_data['owner-filter'] != '':
        #     flock = form_data['owner-filter']
        #     content['owner_filter_value'] = owner

        if form_data['coat-filter'].lower() != "any":
            coat_color = form_data['coat-filter'].lower()
            content['coat_color_filter_value'] = coat_color

        sex_filter = form_data['sex-filter']
        content['sex_filter'] = sex_filter
        only_alive_animals = not "all_animals" in form_data.keys()

        # animals = db.get_all_animals(name=name, reg_num=reg_num, flock=flock, coat_color=coat_color, sex_filter=sex_filter, only_alive_animals=only_alive_animals, owner = owner_member_number)
        animals = db.get_all_animals(name=name, reg_num=reg_num, flock=flock, coat_color=coat_color,
                                     sex_filter=sex_filter, only_alive_animals=only_alive_animals)

        if len(animals) > 500:
            content['err_message'] = "More than 500 animals found, please refine your search."
            return render_template("/animalSearch/animal_search.html", **content)
        else:
            content['animals'] = animals

        return render_template("/animalSearch/animal_search.html", **content)

    return render_template("/animalSearch/animal_search.html", **content)


@app1.route("/births/", methods=('GET', 'POST'))
@login_required
def birth_details():

    if request.method == 'POST':

        content = request.form.to_dict()

        if content['dob'] == '':
            flash("Please enter a date of birth.")
            return redirect(url_for("app1.birth_details", **content))

        session['chosen_sire'] = content['sire']

        return redirect(url_for('app1.offspring', **content))

    content = request.args.to_dict()

    content['conceptionTypes'] = db.get_conception_types()

    now = datetime.now()
    content['date'] = now.strftime("%Y-%m-%d")  # get current date

    if current_user.contact_id != '':
        content['sires'] = db.all_alive_sires_owned_currently(contact_id=current_user.contact_id)
    elif current_user.company_id != '':
        content['sires'] = db.all_alive_sires_owned_currently(company_id=current_user.company_id)
    else:
        raise Exception("User has no contact or company ID")

    # get contact or company id to get dams
    if current_user.contact_id != '':
        content['dams'] = db.all_alive_dams_owned_currently(contact_id=current_user.contact_id)
    elif current_user.company_id != '':
        content['dams'] = db.all_alive_dams_owned_currently(company_id=current_user.company_id)
    else:
        raise Exception("User has no contact or company ID")

    try:
        chosen_sire = session['chosen_sire']
    except Exception as e:
        chosen_sire = ''

    content['chosen_sire'] = chosen_sire

    return render_template("/birthing/birthdetails.html", **content)


@app1.route("/changecontact/", methods=('GET', 'POST'))
@login_required
def change_contact_info():

    if request.method == 'POST':

        # define prefixes to pull data from form
        prefix_first_name = "contact_first_name_"
        prefix_middle_name = "contact_middle_name_"
        prefix_last_name = "contact_last_name_"
        prefix_phone = "phone_"
        prefix_email = "email_"
        prefix_premise_number = "premise_number_"
        prefix_address_1 = "address_1_"
        prefix_address_2 = "address_2_"
        prefix_city = "city_"
        prefix_state = "state_"
        prefix_postcode = "postcode_"

        form_data = request.form.to_dict()
        checked = [q for q in form_data.keys() if q.startswith("cb")]

        contact_content = list()

        for i, cb in enumerate(checked):
            row = dict()  # create list for single row
            row_num = cb.split("_")[1]  # get the row number
            # fill row data
            row["first_name"] = form_data[prefix_first_name + row_num]
            row["middle_name"] = form_data[prefix_middle_name + row_num]
            row["last_name"] = form_data[prefix_last_name + row_num]
            row["phone"] = form_data[prefix_phone + row_num]
            row["email"] = form_data[prefix_email + row_num]
            row["premise_number"] = form_data[prefix_premise_number + row_num]
            row["address_1"] = form_data[prefix_address_1 + row_num]
            row["address_2"] = form_data[prefix_address_2 + row_num]
            row["city"] = form_data[prefix_city + row_num]
            row["state"] = form_data[prefix_state + row_num]
            row["postcode"] = form_data[prefix_postcode + row_num]

            contact_content.append(row)

        session["contact_content"] = contact_content
        return redirect(url_for('app1.change_contact_info_verify'))

    session["user_info"] = db.get_contact_info(current_user.id)

    states = db.get_states()

    return render_template("/contactInfo/change_contact_info.html", user_info=session["user_info"], state_info=states)


@app1.route("/change_contact_verify/", methods=('GET', 'POST'))
@login_required
def change_contact_info_verify():
    states = db.get_states()

    if request.method == 'POST':
        form_data = request.form.to_dict()

        # get number of iterations to run
        idx = 1
        cont = True
        while cont:
            if f"old_contact_first_name_{idx}" not in form_data.keys():
                cont = False
            else:
                idx += 1

        # prefixes
        new = "new_"
        old = "old_"
        # prefixes!
        prefix_contact_first_name = "contact_first_name_"
        prefix_contact_middle_name = "contact_middle_name_"
        prefix_contact_last_name = "contact_last_name_"
        prefix_phone = "phone_"
        prefix_email = "email_"
        prefix_premise_number = "premise_number_"
        prefix_address_1 = "address_1_"
        prefix_address_2 = "address_2_"
        prefix_city = "city_"
        prefix_state = "state_"
        prefix_postcode = "postcode_"

        # prefixes
        data = list()
        # for i, c in checked:
        for i in range(1, idx):
            old_fn = form_data[old + prefix_contact_first_name + str(i)]
            old_mn = form_data[old + prefix_contact_middle_name + str(i)]
            old_ln = form_data[old + prefix_contact_last_name + str(i)]
            old_phone = form_data[old + prefix_phone + str(i)]
            old_email = form_data[old + prefix_email + str(i)]
            old_premise_number = form_data[old + prefix_premise_number + str(i)]
            old_address_1 = form_data[old + prefix_address_1 + str(i)]
            old_address_2 = form_data[old + prefix_address_2 + str(i)]
            old_city = form_data[old + prefix_city + str(i)]
            old_state = form_data[old + prefix_state + str(i)]
            old_postcode = form_data[old + prefix_postcode + str(i)]

            new_fn = form_data[new + prefix_contact_first_name + str(i)]
            new_mn = form_data[new + prefix_contact_middle_name + str(i)]
            new_ln = form_data[new + prefix_contact_last_name + str(i)]
            new_phone = form_data[new + prefix_phone + str(i)]
            new_email = form_data[new + prefix_email + str(i)]
            new_premise_number = form_data[new + prefix_premise_number + str(i)]
            new_address_1 = form_data[new + prefix_address_1 + str(i)]
            new_address_2 = form_data[new + prefix_address_2 + str(i)]
            new_city = form_data[new + prefix_city + str(i)]
            new_state = form_data[new + prefix_state + str(i)]
            new_postcode = form_data[new + prefix_postcode + str(i)]

            row = [old_fn, old_mn, old_ln, old_phone, old_email, old_premise_number, old_address_1, old_address_2, old_city,
                   old_state, old_postcode, new_fn, new_mn, new_ln, new_phone, new_email, new_premise_number, new_address_1, new_address_2,
                   new_city, new_state, new_postcode]

            data.append(row)

        result = stage.stage_contact_updates(current_user, data)

        if result:
            # good!
            flash("Data successfully submitted. Waiting for registrar approval. "
                  "No further action from you is required.")
            # del session["contact_content"]  # delete key to save space in user cookies
            return redirect(url_for("app1.home"))
        else:
            # bad!

apps/app1/templates/animalSearch/animal_search.html
{% extends "layouts/base.html" %}

{% block title%}
Animal Search
{% endblock %}

{% block content %}
{# this script line gets the jquery library to use for this page #}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{# script for filtering table by sex #}
{# <script>
    function filterTable() {
        // get filters
        var sexFilter = document.getElementById("sex-filter").value;
        var nameFilter = document.getElementById("name-filter").value.toLowerCase();
        var regNumFilter = document.getElementById("regNum-filter").value.toLowerCase();
        var flockFilter = document.getElementById("flock-filter").value.toLowerCase();
        var coatFilter = document.getElementById("coat-filter").value.toLowerCase();

        var tableRows = document.getElementsByClassName("data-row");

        // Meat and taters' of the filtering
        for (var i = 0; i < tableRows.length; i++) {
            var rowName = tableRows[i].dataset.name.toLowerCase();
            var rowRegNum = tableRows[i].dataset.regnum.toLowerCase();
            var rowSex = tableRows[i].dataset.sex;
            var rowFlock = tableRows[i].dataset.flock.toLowerCase();
            var rowCoat = tableRows[i].dataset.coat.toLowerCase();

            var nameMatch = rowName.includes(nameFilter);
            var regNumMatch = rowRegNum.includes(regNumFilter);
            var flockMatch = rowFlock.includes(flockFilter);
            var coatMatch = rowCoat.includes(coatFilter);

            // check if sex matches
            var sexMatch;
            if (sexFilter === "all" || sexFilter === rowSex) {
                sexMatch = true;
            } else {
                sexMatch = false;
            }

            if (nameMatch && regNumMatch && sexMatch && flockMatch && coatMatch) {
                tableRows[i].style.display = "table-row";
            } else {
                tableRows[i].style.display = "none";
            }
        }
    }
</script> #}
<style>
        .my-div {
            padding: 20px; /* Apply 20 pixels of padding on all sides */
        }
</style>
<div class="my-div">
        {# here is where the search parameters are #}
    <form action="{{ url_for('app1.animal_search') }}" method="post">
        <label for="name-filter">Filter by Name:</label>
        {% if name_filter_value %}
            <input type="text" id="name-filter" name="name-filter" oninput="filterTable()" value="{{ name_filter_value }}">
        {% else %}
            <input type="text" id="name-filter" name="name-filter" oninput="filterTable()">
        {% endif %}
        <br>
        <br>
        <label for="regNum-filter">Filter by Registration Number:</label>
        {% if reg_num_filter_value %}
            <input type="text" id="regNum-filter" name="regNum-filter" oninput="filterTable()" value="{{ reg_num_filter_value }}">
        {% else %}
            <input type="text" id="regNum-filter" name="regNum-filter" oninput="filterTable()" value="{{ reg_num_filter_value }}">
        {% endif %}
        <br>
        <br>
        <label for="flock-filter">Filter by Flock Prefix:</label>
        {% if flock_filter_value %}
            <input type="text" id="flock-filter" name="flock-filter" oninput="filterTable()" value="{{ flock_filter_value }}">
        {% else %}
            <input type="text" id="flock-filter" name="flock-filter" oninput="filterTable()">
        {% endif %}
        <br>
<!--        <br>-->
<!--        <label for="owner-filter">Filter by Owner Member Number:</label>-->
<!--        {% if flock_filter_value %}-->
<!--            <input type="text" id="owner-filter" name="owner-filter" oninput="filterTable()" value="{{ owner }}">-->
<!--        {% else %}-->
<!--            <input type="text" id="owner-filter" name="owner-filter" oninput="filterTable()">-->
<!--        {% endif %}-->
<!--        <br>-->
<!--        <br>-->
        <label for="coat-filter">Filter by Coat Color:</label>
        <select name="coat-filter">
            <option id="coat-filter" name="coat-filter" value="Any" oninput="filterTable()" selected>Any</option>
            {% for coat_color in coat_colors %}
                {% if coat_color.lower() == coat_color_filter_value.lower() %}
                <option id="coat-filter" name="coat-filter" value="{{ coat_color }}" oninput="filterTable()" selected>{{ coat_color }}</option>
                {% else %}
                <option id="coat-filter" name="coat-filter" value="{{ coat_color }}" oninput="filterTable()">{{ coat_color }}</option>
                {% endif %}
            {% endfor %}
        </select>

        {# filter by sex #}
        <br>
        <br>
        <label for="sex-filter">Filter by Sex:</label>

        <select id="sex-filter" name="sex-filter">
            <option value="all">All</option>
            {% for sex in sexes %}
                {% if sex == sex_filter %}
                <option value="{{ sex }}" selected>{{ sex }}</option>
                {% else %}
                <option value="{{ sex }}">{{ sex }}</option>
                {% endif %}
            {% endfor %}
        </select>

        <br>
        <br>
        {# choose all animals or dead animals #}
        <div>
            <label for="all_animals">Search All Animals (including dead)</label>
            <input type="checkbox" name="all_animals" id="all_animals" unchecked>
        </div>

        <br>
        <br>
        <button type="submit" class="submit-button" id="search">Search</button>
    </form>
</div>
{% if err_message %}
    <div>
        <h1>{{ err_message }}</h1>
        <br>
    </div>
    {% endif %}
<div class="container">
    {# end search parameters #}
    <div style="overflow:auto;width:800px;height:400px;" id="table-holder">
        {% if animals %}
        <table class="fl-table">
            <thead>
                <tr>
                    <th>Pedigree</th>
                    <th>Registration #</th>
                    <th>Flock</th>
                    <th>Name</th>
                    <th>Birth date</th>
                    <th>Death date</th>
                    <th>Sex</th>
                    <th>Coat Color</th>
                </tr>
            </thead>
            <tbody>

            {% for animal_id, reg_num, prefix, name, birth_date, death_date, sex_name, coat_color in animals %}
                <tr class="data-row" data-name="{{ name }}" data-regNum="{{ reg_num }}" data-flock="{{ prefix }}" data-coat="COAT_COLOR">
                    <td><button type="submit" class="submit-button" id="pedigree_{{ loop.index }}">Pedigree</button></td>
                    <td><input type="text" name="regnum_{{ loop.indx }}" value="{{ reg_num }}" readonly></td>
                    <td><input type="text" name="flock_{{ loop.index }}" value="{{ prefix }}" readonly></td>
                    <td><input type="text" name="name_{{ loop.index }}" value="{{ name }}" readonly></td>
                    <td><input type="date" name="dob_{{ loop.index }}" value="{{ birth_date }}" readonly></td>
                    {% if death_date == ''%}
                        <td><input type="date" name="dod_{{ loop.index }}" value="Alive" readonly></td>
                    {% else %}
                        <td><input type="date" name="dod_{{ loop.index }}" value="{{ death_date }}" readonly></td>
                    {% endif %}
                    <td><input type="text" name="sex_{{ loop.index }}" value="{{ sex_name }}" readonly></td>
                    <td><input type="text" name="coat_color_{{ loop.index }}" value="{{ coat_color }}" readonly></td>
                </tr>
                <script>
                    $(document).ready(function() {
                        $("#pedigree_{{ loop.index }}").click(function() {
                            window.open("/pedigree/{{ animal_id }}", "_blank");
                        });
                    });
                </script>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h1>Please Enter Search Parameters</h1>
        {% endif %}
    </div>
</div>

<script>
    function updateDivWidth() {
      // Get the current browser window width
      var windowWidth = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;

      // Calculate the new width for the div (e.g., 90% of the window width)
      var newWidth = Math.floor(windowWidth * 0.9);

      // Get a reference to the div element
      var divElement = document.getElementById('table-holder'); // Replace 'yourDivId' with the actual ID of your div

      // Set the new width for the div
      divElement.style.width = newWidth + 'px';
    }

    // Call the function initially to set the div's width
    updateDivWidth();

    // Add an event listener for the window resize event
    window.addEventListener('resize', updateDivWidth);
</script>
{% endblock %}